name : Build and deploy Node.js app to Azure Web App - nodejs-project
on:
  push:
    branches:
       - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
